# Generated by Django 5.0.6 on 2024-07-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='cast_time',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spell',
            name='components',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spell',
            name='duration',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spell',
            name='higher_level',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='materiais',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='ritual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spell',
            name='school',
            field=models.CharField(choices=[('abjuração', 'Abjuração'), ('adivinhação', 'Adivinhação'), ('convocação', 'Convocação'), ('encantamento', 'Encantamento'), ('evocação', 'Evocação'), ('ilusão', 'Ilusão'), ('necromancia', 'Necromancia'), ('transmutação', 'Transmutação')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spell',
            name='level',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')]),
        ),
        migrations.AlterField(
            model_name='spell',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='spell',
            name='range',
            field=models.CharField(max_length=50),
        ),
    ]
