# Generated by Django 5.0.6 on 2024-07-08 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_spell_cast_time_spell_components_spell_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell',
            old_name='materiais',
            new_name='material',
        ),
    ]
