# Generated by Django 5.0.6 on 2024-07-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='criado_em',
            field=models.DateField(auto_now_add=True, default='2024-07-26'),
            preserve_default=False,
        ),
    ]
