# Generated by Django 5.0.6 on 2024-07-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_venda_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluido', 'Concluido'), ('expirado', 'Expirado'), ('reembolsado', 'Re-embolsado')], default=(), max_length=12),
        ),
    ]
